name: darkages

services:

  db:
    image: mariadb:11
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: mariadb-root-password
      MARIADB_DATABASE: darkages
      MARIADB_USER: mariadb-user
      MARIADB_PASSWORD: mariadb-password
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql

  adminer:
    image: adminer
    container_name: l2c1-adminer
    restart: always
    ports:
      - "9090:8080"
    depends_on:
      - db

volumes:
  mariadb:

